DROP DATABASE IF EXISTS examenPHP;
CREATE DATABASE IF NOT EXISTS examenPHP;

USE examenPHP;
DROP TABLE IF EXISTS usuaris;
CREATE TABLE IF NOT EXISTS usuaris (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nom VARCHAR(30) NOT NULL,
	ciutat VARCHAR(30) NOT NULL,
	numero INT NOT NULL
);